### ISSUE TITLE
dmesg push to cloud

### ISSUE THREAD

**Issue by dheerajdevalekar** [dheerajdevalekar/gateway_backup_access#1]
@Ashwini-Darekar Kindly do the following Task;

- [ ] Make a Virtual Route, so that atleast proper format of DMESG are sent to cloud. In the Format it contains its panel_number(IP if possible)
- [ ] Make a NEW repo, to collect the Data sent from Gateway via API.

**Comment by Ashwini-Darekar** [comment]
create a function to send demsg on cloud 
please review @dheerajdevalekar
